import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import SmokeyCursor from "./Components/SmokeyCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
      >
        {/* 🔥 Smokey Cursor Overlay */}
        <SmokeyCursor />

        {/* 🎨 Radial Gradient Background */}
        <div
          className="absolute inset-0 -z-10"
          style={{
            background: "radial-gradient(125% 125% at 50% 90%, #000000 40%, #0d1a36 100%)",
          }}

        />

        {/* 🧭 Navbar */}
        <Navbar />

        {/* 🧩 Main Content */}
        <main className="min-h-[calc(100vh-68px)] relative z-10">
          {children}
        </main>

        {/* 🦶 Footer */}
        <Footer />
      </body>
    </html>
  );
}
